# Generated by Django 5.1 on 2024-12-20 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tech_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, max_length=255, null=True)),
                ('filial', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=100, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.CharField(max_length=100)),
                ('situacao_data_fim', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('centro_custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_assets.costcenter')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_persons.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
