# Generated by Django 5.1 on 2024-08-10 21:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ativo',
                'verbose_name_plural': 'Tipos de Ativo',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100, null=True)),
                ('numero', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versao', models.CharField(max_length=50)),
                ('licenca', models.CharField(max_length=100)),
                ('data_expiracao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartado', 'Descartado'), ('em_estoque', 'Em Estoque')], default='em_estoque', max_length=20)),
                ('localizacao', models.CharField(max_length=100)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.assettype')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.costcenter')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.manufacturer')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=datetime.datetime.now)),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='emprestado', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='tech_assets.asset')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_asset', to=settings.AUTH_USER_MODEL)),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_asset', to='tech_assets.costcenter')),
            ],
            options={
                'verbose_name': 'Alocação de Ativo',
                'ordering': ['-data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_de_campo', models.CharField(choices=[('text', 'Texto'), ('number', 'Numérico'), ('boolean', 'Booleano')], max_length=10)),
                ('ordem', models.IntegerField()),
                ('tipo_de_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.assettype')),
            ],
            options={
                'verbose_name': 'Campo Personalizado',
                'verbose_name_plural': 'Campos Personalizados',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numerico', models.FloatField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.asset')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.customfield')),
            ],
            options={
                'verbose_name': 'Valore de Campo Personalizado',
                'verbose_name_plural': 'Valores de Campos Personalizados',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local_pai', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='tech_assets.location')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.asset')),
            ],
            options={
                'verbose_name': 'Manutenção',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('switch', 'Switch'), ('roteador', 'Roteador'), ('firewall', 'Firewall')], max_length=20)),
                ('endereco_ip', models.GenericIPAddressField()),
                ('mascara_rede', models.CharField(max_length=15)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.asset')),
            ],
            options={
                'verbose_name': 'Dispositivo de Rede',
                'verbose_name_plural': 'Dispositivos de Rede',
            },
        ),
    ]
