# Generated by Django 5.1 on 2024-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='descricao',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
