# Generated by Django 5.1 on 2024-08-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.accessory')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.movement')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='acessorios',
            field=models.ManyToManyField(blank=True, null=True, through='tech_assets.MovementAccessory', to='tech_assets.accessory'),
        ),
    ]
