# Generated by Django 5.1 on 2024-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnterm',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
