# Generated by Django 5.1 on 2024-08-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='numero',
            field=models.CharField(),
        ),
    ]
