# Generated by Django 5.1 on 2024-08-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnterm',
            old_name='ass_usuario',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='returnterm',
            name='ass_usuario_recebedor',
        ),
        migrations.RemoveField(
            model_name='returnterm',
            name='usuario',
        ),
    ]
