# Generated by Django 5.1 on 2024-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='data_prevista_fim',
            field=models.DateField(),
        ),
    ]
