# Generated by Django 5.1 on 2024-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='data_garantia',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='data_instalacao_so',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='ultimo_logon',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='ultimo_scan',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
