# Generated by Django 5.1 on 2024-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ativos',
        ),
        migrations.AlterField(
            model_name='asset',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
