# Generated by Django 5.1 on 2024-08-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_alter_maintenance_data_prevista_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='data_prevista_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReturnTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned', to='tech_assets.movement')),
            ],
        ),
        migrations.CreateModel(
            name='TermRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('aprovacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='tech_assets.approval')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='tech_assets.movement')),
            ],
        ),
    ]
