# Generated by Django 5.1 on 2024-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_alter_returnterm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementaccessory',
            name='quantidade_devolvida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
