# Generated by Django 5.1 on 2024-08-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_alter_costcenter_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
