# Generated by Django 5.1 on 2024-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_movementaccessory_movement_acessorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='acessorios',
            field=models.ManyToManyField(blank=True, through='tech_assets.MovementAccessory', to='tech_assets.accessory'),
        ),
    ]
