# Generated by Django 5.1 on 2024-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_alter_assettype_descricao_alter_assettype_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
