# Generated by Django 5.1 on 2024-08-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_rename_ass_usuario_returnterm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnterm',
            name='observacao',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
