# Generated by Django 5.1 on 2024-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_alter_assetinfo_data_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='dias_atraso',
            field=models.IntegerField(default=0),
        ),
    ]
