# Generated by Django 5.1 on 2024-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0002_remove_cart_ativos_alter_asset_patrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ativos',
            field=models.ManyToManyField(through='tech_assets.AssetCart', to='tech_assets.asset'),
        ),
    ]
