# Generated by Django 5.1 on 2024-08-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0003_maintenance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Manutenção'},
        ),
    ]
