# Generated by Django 5.1 on 2024-08-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0003_alter_maintenance_data_prevista_fim_returnterm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termres',
            old_name='status',
            new_name='status_resposta',
        ),
        migrations.AddField(
            model_name='termres',
            name='aceite_usuario',
            field=models.CharField(choices=[('aceito', 'Aceito'), ('pendente', 'pendente'), ('recusado', 'Recusado')], default='pendente', max_length=100),
        ),
    ]
