# Generated by Django 5.1 on 2024-08-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0003_cart_ativos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ativos',
        ),
    ]
