# Generated by Django 5.1 on 2024-08-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0003_alter_maintenance_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
