# Generated by Django 5.1 on 2024-08-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0004_alter_maintenance_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
