# Generated by Django 5.1 on 2024-08-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0004_remove_cart_ativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_assets.assetmodel'),
        ),
    ]
