# Generated by Django 5.1 on 2024-08-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0004_alter_returnterm_usuario_recebedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementaccessory',
            name='quantidade_devolvida',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
