# Generated by Django 5.1 on 2024-08-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0005_alter_movementaccessory_quantidade_devolvida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('pendente_aprovacao', 'Aprovação Pendente'), ('pendente_entrega', 'Pendente Entrega'), ('em_devolucao', 'Devolução em Andamento'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='pendente_aprovacao', max_length=20),
        ),
    ]
