# Generated by Django 5.1 on 2024-09-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0006_alter_movement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='data_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='data_instalacao_so',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='ultimo_logon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='ultimo_scan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
