# Generated by Django 5.1 on 2024-08-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0006_remove_asset_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='ativos',
        ),
    ]
