# Generated by Django 5.1 on 2024-08-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0007_alter_maintenance_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='departamento',
            new_name='centro_de_custo',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
