# Generated by Django 5.1 on 2024-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0007_alter_assetinfo_data_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
