# Generated by Django 5.1 on 2024-08-11 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0008_rename_departamento_asset_centro_de_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_assets.costcenter'),
        ),
    ]
