# Generated by Django 5.1 on 2024-09-10 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0008_termo_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='data_movimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
