# Generated by Django 5.1 on 2024-08-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0008_loan_ativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_assets.assettype'),
        ),
    ]
