# Generated by Django 5.1 on 2024-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0009_asset_patrimonio_alter_asset_centro_de_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='site',
            field=models.CharField(choices=[('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartado', 'Descartado'), ('em_estoque', 'Em Estoque')], default='rio_quente', max_length=100),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='numero',
            field=models.CharField(unique=True),
        ),
    ]
