# Generated by Django 5.1 on 2024-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0009_assetmodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
