# Generated by Django 5.1 on 2024-08-11 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0010_asset_site_alter_costcenter_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='localizacao',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizacao', to='tech_assets.location'),
        ),
    ]
