# Generated by Django 5.1 on 2024-08-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0010_alter_asset_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='ativos',
        ),
    ]
