# Generated by Django 5.1 on 2024-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0011_remove_loan_ativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ativos',
            field=models.ManyToManyField(through='tech_assets.LoanAsset', to='tech_assets.asset'),
        ),
    ]
