# Generated by Django 5.1 on 2024-09-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0011_alter_assetinfo_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinfo',
            old_name='data_instalacao_so',
            new_name='data_instalacao_plataforma',
        ),
        migrations.RenameField(
            model_name='assetinfo',
            old_name='licenca_so',
            new_name='licenca_plataforma',
        ),
        migrations.RenameField(
            model_name='assetinfo',
            old_name='so',
            new_name='plataforma',
        ),
        migrations.RenameField(
            model_name='assetinfo',
            old_name='versao_so',
            new_name='versao_plataforma',
        ),
    ]
