# Generated by Django 5.1 on 2024-08-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0011_alter_asset_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
