# Generated by Django 5.1 on 2024-08-11 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0012_alter_asset_numero_serie_alter_location_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_assets.costcenter'),
        ),
    ]
