# Generated by Django 5.1 on 2024-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0012_rename_data_instalacao_so_assetinfo_data_instalacao_plataforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinfo',
            name='data_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
