# Generated by Django 5.1 on 2024-08-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0013_alter_asset_centro_de_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='centro_de_custo',
        ),
    ]
