# Generated by Django 5.1 on 2024-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0013_assetinfo_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='numero',
            field=models.CharField(blank=True, null=True),
        ),
    ]
