# Generated by Django 5.1 on 2024-08-11 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0014_remove_asset_centro_de_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='localizacao',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_allocated_asset', to='tech_assets.location'),
        ),
    ]
