# Generated by Django 5.1 on 2024-10-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0014_alter_costcenter_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogonInAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_logon', models.DateField(blank=True, null=True)),
                ('ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logon_asset', to='tech_assets.asset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logon_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
