# Generated by Django 5.1 on 2024-08-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0015_remove_asset_localizacao_assetallocation_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetallocation',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='asset',
            name='localizacao',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_assets.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='site',
            field=models.CharField(choices=[('rio_quente', 'Rio Quente'), ('costa_do_sauipe', 'Costa do Sauipe')], default='rio_quente', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_assets.assettype'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
