# Generated by Django 5.1 on 2024-10-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0015_logoninasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoninasset',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
