# Generated by Django 5.1 on 2024-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0015_alter_loanasset_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('em_estoque', 'Em Estoque'), ('descartado', 'Descartado'), ('separado', 'Separado')], default='em_estoque', max_length=20),
        ),
    ]
