# Generated by Django 5.1 on 2024-10-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0016_logoninasset_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='ultimo_logon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='ultimo_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logoninasset',
            name='data_logon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
