# Generated by Django 5.1 on 2024-08-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0016_remove_assetallocation_localizacao_asset_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('em_estoque', 'Em Estoque'), ('descartado', 'Descartado')], default='em_estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='valor_aquisicao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
