# Generated by Django 5.1 on 2024-08-11 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0017_alter_asset_data_aquisicao_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_assets.manufacturer'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='valor_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
