# Generated by Django 5.1 on 2024-10-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0017_alter_assetinfo_data_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
