# Generated by Django 5.1 on 2024-08-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0018_alter_asset_fabricante_alter_asset_valor_aquisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='ordem',
        ),
    ]
