# Generated by Django 5.1 on 2024-10-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0018_alter_assetmodel_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termo_movimentacao', to='tech_assets.movement'),
        ),
    ]
