# Generated by Django 5.1 on 2024-10-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0019_alter_termo_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('em_uso', 'Em Uso'), ('transferido', 'Transferido'), ('em_manutencao', 'Em Manutenção'), ('em_estoque', 'Em Estoque'), ('baixado', 'Baixado'), ('separado', 'Separado'), ('nao_devolvido', 'Não Devolvido')], default='em_estoque', max_length=20),
        ),
    ]
