# Generated by Django 5.1 on 2024-08-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0019_remove_customfield_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='chamado_top_desk',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
