# Generated by Django 5.1 on 2024-08-11 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0020_assetallocation_chamado_top_desk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='custom_field',
        ),
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='asset',
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='data_devolucao_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ApprovalAssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_aprovacao', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('pendente', 'Pendente')], default='emprestado', max_length=20)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='tech_assets.assetallocation')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='CustomFieldValue',
        ),
    ]
