# Generated by Django 5.1 on 2024-10-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0020_alter_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(editable=False, max_length=12, unique=True)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assetcart',
            options={'verbose_name': 'Ativo / Carrinho', 'verbose_name_plural': 'Ativos / Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-data_movimento'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='movementaccessory',
            options={'verbose_name': 'Movimentação / Acessório', 'verbose_name_plural': 'Movimentações / Acessório'},
        ),
        migrations.AlterModelOptions(
            name='movementasset',
            options={'verbose_name': 'Movimentação / Ativo', 'verbose_name_plural': 'Movimentações / Ativo'},
        ),
        migrations.AddField(
            model_name='termo',
            name='conteudo_termo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='tech_assets.conteudotermo'),
        ),
    ]
