# Generated by Django 5.1 on 2024-08-11 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0021_remove_customfieldvalue_custom_field_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='status',
            field=models.CharField(choices=[('pendente_aprovação', 'Aprovação Pendente'), ('emprestado', 'Emprestado'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='pendente_aprovação', max_length=20),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_aprovacao', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='tech_assets.assetallocation')),
            ],
        ),
        migrations.DeleteModel(
            name='ApprovalAssetAllocation',
        ),
    ]
