# Generated by Django 5.1 on 2024-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0022_alter_termo_conteudo_termo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudotermo',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferência'), ('emprestimo', 'Empréstimo'), ('baixa', 'Baixa')], default='emprestimo', max_length=100),
        ),
    ]
