# Generated by Django 5.1 on 2024-10-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0023_conteudotermo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='conteudo_termo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='tech_assets.conteudotermo'),
        ),
    ]
