# Generated by Django 5.1 on 2024-10-28 14:43

import apps.tech_assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0024_alter_termo_conteudo_termo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='conteudo_termo',
            field=models.ForeignKey(default=apps.tech_assets.models.get_latest_termo_version, on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='tech_assets.conteudotermo'),
        ),
    ]
