# Generated by Django 5.1 on 2024-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_assets', '0027_alter_termo_conteudo_termo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudotermo',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='termo',
            name='aceite_usuario',
            field=models.CharField(choices=[('aceito', 'Aceito'), ('pendente', 'Pendente'), ('recusado', 'Recusado'), ('pendente_aceite_novos_termos', 'Pendente Aceitação de Novos Termos')], default='pendente', max_length=100),
        ),
    ]
