# Generated by Django 5.1 on 2024-09-02 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tech_assets', '0006_alter_movement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPOS',
            fields=[
                ('id_gpos', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID GPOS')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pos_number', models.IntegerField(verbose_name='Número do POS')),
                ('only_pre_sales', models.BooleanField(default=False, verbose_name='Apenas Pré-Vendas')),
                ('primary_pdv', models.BooleanField(default=False, verbose_name='PDV Primário')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('creator_user', models.CharField(max_length=255, verbose_name='Usuário Criador')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('computer_type', models.CharField(max_length=100, verbose_name='Tipo de Computador')),
                ('blocked', models.BooleanField(default=False)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.asset')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja_gpos', to='tech_assets.location', verbose_name='Loja')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdv_gpos', to='tech_assets.location', verbose_name='PDV')),
            ],
            options={
                'verbose_name': 'GPOS',
                'verbose_name_plural': 'GPOSs',
                'ordering': ['-creation_date'],
            },
        ),
    ]
