# Generated by Django 5.1 on 2024-12-20 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tech_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPOS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID GPOS')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('pos_number', models.IntegerField(verbose_name='Número do POS')),
                ('only_pre_sales', models.BooleanField(default=False, verbose_name='Apenas Pré-Vendas')),
                ('primary_pdv', models.BooleanField(default=False, verbose_name='PDV Primário')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('creator_user', models.CharField(max_length=100, verbose_name='Usuário Criador')),
                ('last_update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização MV')),
                ('username_last_user_logon', models.CharField(max_length=100, null=True, verbose_name='Último usuário a fazer logon')),
                ('code_last_user_logon', models.CharField(max_length=100, null=True, verbose_name='Código do último usuário a fazer logon')),
                ('last_logon_date', models.DateTimeField(db_index=True, null=True, verbose_name='Data último logon MV')),
                ('computer_type', models.CharField(max_length=100, verbose_name='Tipo de Computador')),
                ('blocked', models.BooleanField(db_index=True, default=False)),
                ('is_mac', models.BooleanField(db_index=True, default=False)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assets.asset')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja_gpos', to='tech_assets.location', verbose_name='Loja')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdv_gpos', to='tech_assets.location', verbose_name='PDV')),
            ],
            options={
                'verbose_name': 'GPOS',
                'verbose_name_plural': 'GPOSs',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado', models.CharField(blank=True, max_length=100, null=True)),
                ('existe_novo_pdv', models.BooleanField(default=False)),
                ('concluida', models.BooleanField(default=False)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(null=True)),
                ('gpos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move_gpos.gpos')),
                ('loja_nova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja_nova_request', to='tech_assets.location', verbose_name='Nova Loja')),
                ('pdv_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdv_atual_request', to='tech_assets.location', verbose_name='PDV Atual')),
                ('pdv_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdv_novo_request', to='tech_assets.location', verbose_name='Novo PDV')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
