# Generated by Django 5.1 on 2024-09-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpos',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
