# Generated by Django 5.1 on 2024-08-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='gpos',
        ),
        migrations.RemoveField(
            model_name='request',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='GPOS',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
