# Generated by Django 5.1 on 2024-09-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0002_alter_gpos_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpos',
            old_name='id_gpos',
            new_name='id',
        ),
    ]
