# Generated by Django 5.1 on 2024-09-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0003_rename_id_gpos_gpos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpos',
            name='pos_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
