# Generated by Django 5.1 on 2024-09-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0004_gpos_pos_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpos',
            name='pos_name',
        ),
    ]
