# Generated by Django 5.1 on 2024-09-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0005_remove_gpos_pos_name'),
        ('tech_assets', '0008_termo_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpos',
            name='is_mac',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado', models.CharField(blank=True, max_length=100, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(auto_now=True)),
                ('gpos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move_gpos.gpos')),
                ('loja_nova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja_nova_request', to='tech_assets.location', verbose_name='Nova Loja')),
                ('pdv_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdv_atual_request', to='tech_assets.location', verbose_name='PDV Atual')),
                ('pdv_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdv_novo_request', to='tech_assets.location', verbose_name='Novo PDV')),
            ],
        ),
    ]
