# Generated by Django 5.1 on 2024-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0006_gpos_is_mac_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='existe_novo_pdv',
            field=models.BooleanField(default=False),
        ),
    ]
