# Generated by Django 5.1 on 2024-09-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0008_request_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpos',
            name='last_update_date',
            field=models.DateTimeField(verbose_name='Última Atualização'),
        ),
    ]
