# Generated by Django 5.1 on 2024-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0009_alter_gpos_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpos',
            name='last_update_date',
            field=models.DateTimeField(null=True, verbose_name='Última Atualização MV'),
        ),
    ]
