# Generated by Django 5.1 on 2024-09-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0010_alter_gpos_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpos',
            name='code_last_user_logon',
            field=models.CharField(max_length=100, null=True, verbose_name='Código do último usuário a fazer logon'),
        ),
        migrations.AddField(
            model_name='gpos',
            name='last_logon_date',
            field=models.DateTimeField(null=True, verbose_name='Data último logon MV'),
        ),
        migrations.AddField(
            model_name='gpos',
            name='username_last_user_logon',
            field=models.CharField(max_length=100, null=True, verbose_name='Último usuário a fazer logon'),
        ),
        migrations.AlterField(
            model_name='gpos',
            name='creator_user',
            field=models.CharField(max_length=100, verbose_name='Usuário Criador'),
        ),
    ]
