# Generated by Django 5.1 on 2024-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0011_gpos_code_last_user_logon_gpos_last_logon_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpos',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização MV'),
        ),
    ]
