# Generated by Django 5.1 on 2024-09-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_gpos', '0012_alter_gpos_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='data_conclusao',
            field=models.DateTimeField(null=True),
        ),
    ]
